### ISSUE TITLE
Publish releases?

### ISSUE THREAD

**Issue by teymour-aldridge** [ahcodedthat/sitemap-from-files#1]
It would be useful (especially for CI workflows) if releases of the binary builds were published (e.g. to Github so that they can be installed by people who don't use Rust, or publish releases to relevant system package managers instead).

**Comment by ahcodedthat** [comment]
Done. [There's now a release `v1.0.0`](https://github.com/ahcodedthat/sitemap-from-files/releases/tag/v1.0.0) with x86_64 binaries for Windows, Linux, and macOS.
